- hosts: media-server

  vars:
    ansible_connection: local
    application_root: "/var/www/"
    application_source:
  tasks:
    - name: install dependenices
      apt:
        name: "{{ item }}"
      with_items:
        - python3
        - python3-pip
        - uwsgi-plugin-python3
        - python3-virtualenv
        - nginx
      become: yes
    -
